-- =====================================================================
-- HRM Suite — COMPLETE SUPABASE SETUP (Phase 1 + Phase 2 in one file)
-- For a NEW, EMPTY Supabase project.   Generated by scripts/build-setup-sql.mjs
--
-- BEFORE RUNNING
--   1. Supabase → Authentication → Users → "Add user" → "Create new user":
--      your admin email + a password, tick "Auto Confirm User".
--   2. Edit the values in "YOUR COMPANY" just below (keep the quotes).
--   3. SQL Editor → New query → paste this WHOLE file → Run.
--      Success ends with:  HRM SETUP COMPLETE
--
-- If anything is wrong (tables already exist, admin login not found) the script stops
-- before changing anything and tells you why.
-- =====================================================================

-- ------------------------- YOUR COMPANY ------------------------------
create temp table hrm_setup as select
  'kmr'                        ::text as company_slug,     -- short id, lowercase, no spaces
  'KMR'                        ::text as company_name,     -- shown in the app
  'KMR Group of Companies'     ::text as legal_name,       -- shown on ID cards and letters
  'KMR'                        ::text as emp_code_prefix,  -- employee codes: KMR-0001, KMR-0002 …
  'hrm.kmr-groups.com'         ::text as web_address,      -- the address the app opens on ('' if none)
  'HO'                         ::text as plant_code,
  'Head Office'                ::text as plant_name,
  'hr@kmr-groups.com'          ::text as admin_email,      -- the login you created in step 1
  'HR Admin'                   ::text as admin_name;
-- ---------------------------------------------------------------------

-- Safety checks: nothing is created if these fail
do $$
declare s record;
begin
  select * into s from hrm_setup;
  if to_regclass('public.tenants') is not null then
    raise exception 'HRM tables already exist in this database. This file is for a new, empty project. To upgrade an existing Phase 1 database, run only supabase/migrations/0002_attendance_leave.sql.';
  end if;
  if not exists (select 1 from auth.users where lower(email) = lower(s.admin_email)) then
    raise exception 'No login found for %. First create it: Authentication → Users → Add user → Create new user (tick Auto Confirm User), then run this file again.', s.admin_email;
  end if;
  if s.company_slug !~ '^[a-z0-9-]{2,30}$' then
    raise exception 'company_slug must be 2–30 lowercase letters, digits or dashes (got %).', s.company_slug;
  end if;
end $$;

-- =====================================================================
-- 0001_foundation.sql
-- =====================================================================
-- =====================================================================
-- HRM Suite — Phase 1: Foundation + Core HR
-- Multi-tenant schema with row-level security on every tenant table.
-- Run in the Supabase SQL editor (or `supabase db push`).
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Tenants (companies) and their domains
-- ---------------------------------------------------------------------
create table public.tenants (
  id              uuid primary key default gen_random_uuid(),
  slug            text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,40}$'),
  name            text not null,                 -- short display name
  legal_name      text,
  logo_path       text,                          -- path in the public "branding" bucket
  primary_color   text not null default '#1F3A5F',
  accent_color    text not null default '#E07A1F',
  address         text,
  phone           text,
  email           text,
  website         text,
  emp_code_prefix text not null default 'EMP',
  emp_code_seq    integer not null default 0,
  settings        jsonb not null default '{}'::jsonb,   -- email_from, whatsapp numbers, id card options...
  active          boolean not null default true,
  created_at      timestamptz not null default now()
);

create table public.tenant_domains (
  domain      text primary key check (domain = lower(domain)),
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  is_primary  boolean not null default false,
  verified    boolean not null default false,
  created_at  timestamptz not null default now()
);
create index on public.tenant_domains(tenant_id);

-- ---------------------------------------------------------------------
-- Organisation masters
-- ---------------------------------------------------------------------
create table public.plants (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  code       text not null,
  name       text not null,
  address    text,
  state      text,
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  unique (tenant_id, code)
);

create table public.departments (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  name       text not null,
  code       text,
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  unique (tenant_id, name)
);

create table public.designations (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  name       text not null,
  grade      text,
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  unique (tenant_id, name)
);

-- ---------------------------------------------------------------------
-- Users (one row per Supabase auth user) and roles
-- ---------------------------------------------------------------------
create table public.app_users (
  id                   uuid primary key references auth.users(id) on delete cascade,
  tenant_id            uuid not null references public.tenants(id) on delete cascade,
  role                 text not null check (role in (
                         'platform_admin','company_admin','hr_manager','hr_executive',
                         'payroll','manager','interviewer','employee')),
  full_name            text not null,
  email                text not null,
  phone                text,
  employee_id          uuid,                     -- FK added after employees table
  must_change_password boolean not null default false,
  active               boolean not null default true,
  created_at           timestamptz not null default now()
);
create index on public.app_users(tenant_id);

-- ---------------------------------------------------------------------
-- Employees
-- ---------------------------------------------------------------------
create table public.employees (
  id                      uuid primary key default gen_random_uuid(),
  tenant_id               uuid not null references public.tenants(id) on delete cascade,
  employee_code           text,
  status                  text not null default 'invited' check (status in (
                            'invited','onboarding','submitted','sent_back','active','inactive','exited')),
  first_name              text not null,
  last_name               text,
  email                   text,
  mobile                  text,
  plant_id                uuid references public.plants(id),
  department_id           uuid references public.departments(id),
  designation_id          uuid references public.designations(id),
  reporting_manager_id    uuid references public.employees(id),
  employment_type         text not null default 'permanent' check (employment_type in (
                            'permanent','probation','fixed_term','trainee','apprentice','contract')),
  category                text not null default 'staff' check (category in ('staff','workman','management')),
  date_of_joining         date,
  date_of_birth           date,
  gender                  text,
  blood_group             text check (blood_group is null or blood_group in ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  photo_path              text,                  -- selfie in the private employee-docs bucket
  emergency_contact_name  text,
  emergency_contact_phone text,
  profile                 jsonb not null default '{}'::jsonb,   -- onboarding sections (personal, family, academic, professional)
  verify_token            text not null unique default encode(gen_random_bytes(16), 'hex'),  -- used by the ID card QR
  created_by              uuid references auth.users(id),
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  unique (tenant_id, employee_code)
);
create index on public.employees(tenant_id, status);

alter table public.app_users
  add constraint app_users_employee_fk foreign key (employee_id) references public.employees(id) on delete set null;

-- Statutory and bank details are kept apart so that managers who can see
-- an employee's profile cannot see these fields.
create table public.employee_private (
  employee_id     uuid primary key references public.employees(id) on delete cascade,
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  pan             text,
  aadhaar_last4   text check (aadhaar_last4 is null or aadhaar_last4 ~ '^[0-9]{4}$'),  -- full Aadhaar is never stored
  uan             text,
  previous_pf_no  text,
  esi_ip_no       text,
  bank_name       text,
  bank_branch     text,
  account_holder  text,
  account_number  text,
  ifsc            text,
  tax_regime      text check (tax_regime is null or tax_regime in ('new','old')),
  updated_at      timestamptz not null default now()
);

create table public.onboarding_invites (
  id                  uuid primary key default gen_random_uuid(),
  tenant_id           uuid not null references public.tenants(id) on delete cascade,
  employee_id         uuid not null references public.employees(id) on delete cascade,
  token_hash          text not null unique,      -- sha256 of the link token; the raw token is only in the link
  status              text not null default 'sent' check (status in (
                        'sent','in_progress','submitted','sent_back','approved','expired','revoked')),
  current_step        integer not null default 0,
  sent_back_sections  text[] not null default '{}',
  hr_comment          text,
  consent_at          timestamptz,
  consent_ip          text,
  reminders_sent      integer not null default 0,
  last_reminder_at    timestamptz,
  expires_at          timestamptz not null default now() + interval '7 days',
  submitted_at        timestamptz,
  reviewed_at         timestamptz,
  reviewed_by         uuid references auth.users(id),
  created_by          uuid references auth.users(id),
  created_at          timestamptz not null default now()
);
create index on public.onboarding_invites(tenant_id, status);
create index on public.onboarding_invites(employee_id);

create table public.employee_documents (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references public.tenants(id) on delete cascade,
  employee_id  uuid not null references public.employees(id) on delete cascade,
  doc_type     text not null,                    -- aadhaar, pan, cheque, qualification, relieving, payslip, experience, photo, selfie, other
  file_path    text not null,                    -- employee-docs/<tenant>/<employee>/<uuid>.<ext>
  file_name    text,
  mime_type    text,
  size_bytes   integer,
  status       text not null default 'uploaded' check (status in ('uploaded','approved','rejected')),
  comment      text,
  uploaded_at  timestamptz not null default now()
);
create index on public.employee_documents(employee_id);

create table public.id_cards (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references public.tenants(id) on delete cascade,
  employee_id  uuid not null references public.employees(id) on delete cascade,
  version      integer not null default 1,
  status       text not null default 'active' check (status in ('active','replaced','revoked')),
  issued_at    timestamptz not null default now(),
  valid_until  date,
  issued_by    uuid references auth.users(id),
  reason       text                               -- new, lost, damaged, data change
);
create index on public.id_cards(employee_id);

-- ---------------------------------------------------------------------
-- Passkeys (Face ID / fingerprint / Windows Hello login)
-- ---------------------------------------------------------------------
create table public.passkeys (
  id            text primary key,                 -- base64url credential id
  user_id       uuid not null references auth.users(id) on delete cascade,
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  public_key    text not null,                    -- base64url COSE public key
  counter       bigint not null default 0,
  transports    text[] not null default '{}',
  device_name   text,
  backed_up     boolean not null default false,
  created_at    timestamptz not null default now(),
  last_used_at  timestamptz
);
create index on public.passkeys(user_id);

-- ---------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------
create table public.notification_templates (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  event           text not null,
  channel         text not null check (channel in ('email','whatsapp')),
  subject         text,
  body            text not null,
  wa_template     text,                           -- approved Meta template name
  wa_language     text default 'en',
  wa_params       text[] not null default '{}',   -- variable names mapped to {{1}}, {{2}}...
  active          boolean not null default true,
  updated_at      timestamptz not null default now(),
  unique (tenant_id, event, channel)
);

create table public.notifications (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  event         text not null,
  channel       text not null check (channel in ('email','whatsapp','sms')),
  recipient     text not null,
  subject       text,
  body          text,
  status        text not null default 'queued' check (status in ('queued','sent','delivered','read','failed','skipped')),
  provider_id   text,
  error         text,
  related_type  text,
  related_id    uuid,
  created_at    timestamptz not null default now(),
  sent_at       timestamptz
);
create index on public.notifications(tenant_id, created_at desc);
create index on public.notifications(provider_id);

-- ---------------------------------------------------------------------
-- Audit log (append-only)
-- ---------------------------------------------------------------------
create table public.audit_log (
  id          bigserial primary key,
  tenant_id   uuid references public.tenants(id) on delete cascade,
  actor_id    uuid,
  action      text not null,                     -- insert / update / delete / semantic e.g. onboarding.approved
  entity      text not null,
  entity_id   text,
  old_data    jsonb,
  new_data    jsonb,
  created_at  timestamptz not null default now()
);
create index on public.audit_log(tenant_id, created_at desc);
create index on public.audit_log(entity, entity_id);

-- =====================================================================
-- Helper functions
-- =====================================================================

-- Tenant of the signed-in user (null for anonymous / service role)
create or replace function public.current_tenant_id() returns uuid
language sql stable security definer set search_path = public as $$
  select tenant_id from public.app_users where id = auth.uid() and active
$$;

create or replace function public.current_role_name() returns text
language sql stable security definer set search_path = public as $$
  select role from public.app_users where id = auth.uid() and active
$$;

create or replace function public.current_employee_id() returns uuid
language sql stable security definer set search_path = public as $$
  select employee_id from public.app_users where id = auth.uid() and active
$$;

-- True when the signed-in user holds any of the given roles.
-- company_admin and platform_admin pass every HR check.
create or replace function public.has_role(variadic roles text[]) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.app_users
    where id = auth.uid() and active
      and (role = any(roles) or role in ('company_admin','platform_admin'))
  )
$$;

create or replace function public.is_hr() returns boolean
language sql stable as $$ select public.has_role('hr_manager','hr_executive') $$;

-- Employees in the signed-in manager's reporting line (direct + indirect)
create or replace function public.is_in_my_team(emp uuid) returns boolean
language sql stable security definer set search_path = public as $$
  with recursive team as (
    select id from public.employees where reporting_manager_id = public.current_employee_id()
    union
    select e.id from public.employees e join team t on e.reporting_manager_id = t.id
  )
  select exists (select 1 from team where id = emp)
$$;

-- Atomically allocate the next employee code, e.g. DEN-PL1-0042
create or replace function public.next_employee_code(p_tenant uuid, p_plant uuid default null) returns text
language plpgsql security definer set search_path = public as $$
declare
  v_prefix text;
  v_seq    integer;
  v_plant  text;
begin
  update public.tenants set emp_code_seq = emp_code_seq + 1
   where id = p_tenant
   returning emp_code_prefix, emp_code_seq into v_prefix, v_seq;
  if v_seq is null then
    raise exception 'tenant % not found', p_tenant;
  end if;
  if p_plant is not null then
    select code into v_plant from public.plants where id = p_plant and tenant_id = p_tenant;
  end if;
  return v_prefix || coalesce('-' || v_plant, '') || '-' || lpad(v_seq::text, 4, '0');
end $$;

-- Generic audit trigger
create or replace function public.audit_row() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_old jsonb := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end;
  v_new jsonb := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end;
  v_row jsonb := coalesce(v_new, v_old);
begin
  if tg_op = 'UPDATE' and v_old = v_new then
    return new;
  end if;
  insert into public.audit_log(tenant_id, actor_id, action, entity, entity_id, old_data, new_data)
  values (
    case when tg_table_name = 'tenants' then (v_row->>'id')::uuid else (v_row->>'tenant_id')::uuid end,
    auth.uid(),
    lower(tg_op),
    tg_table_name,
    coalesce(v_row->>'id', v_row->>'employee_id'),
    v_old,
    v_new
  );
  return coalesce(new, old);
end $$;

create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$ begin new.updated_at := now(); return new; end $$;

create trigger employees_touch before update on public.employees
  for each row execute function public.touch_updated_at();
create trigger employee_private_touch before update on public.employee_private
  for each row execute function public.touch_updated_at();

do $$
declare t text;
begin
  foreach t in array array['tenants','tenant_domains','plants','departments','designations','app_users',
                           'employees','employee_private','onboarding_invites','employee_documents','id_cards',
                           'notification_templates']
  loop
    execute format('create trigger %I after insert or update or delete on public.%I
                    for each row execute function public.audit_row()', t || '_audit', t);
  end loop;
end $$;

-- Default masters for a new tenant
create or replace function public.seed_tenant_defaults(p_tenant uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  insert into public.departments(tenant_id, name, code) values
    (p_tenant,'Production','PRD'),(p_tenant,'Quality','QA'),(p_tenant,'Maintenance','MNT'),
    (p_tenant,'Stores','STR'),(p_tenant,'Production Planning & Control','PPC'),
    (p_tenant,'Human Resources','HR'),(p_tenant,'Accounts & Finance','FIN'),
    (p_tenant,'Purchase','PUR'),(p_tenant,'Engineering','ENG'),(p_tenant,'EHS','EHS')
  on conflict do nothing;
  insert into public.designations(tenant_id, name, grade) values
    (p_tenant,'Operator','W1'),(p_tenant,'Senior Operator','W2'),(p_tenant,'Technician','W3'),
    (p_tenant,'Supervisor','S1'),(p_tenant,'Engineer','S2'),(p_tenant,'Senior Engineer','S3'),
    (p_tenant,'Assistant Manager','M1'),(p_tenant,'Manager','M2'),(p_tenant,'Senior Manager','M3'),
    (p_tenant,'Head of Department','M4')
  on conflict do nothing;
end $$;

-- =====================================================================
-- Row-level security
-- =====================================================================
alter table public.tenants                enable row level security;
alter table public.tenant_domains         enable row level security;
alter table public.plants                 enable row level security;
alter table public.departments            enable row level security;
alter table public.designations           enable row level security;
alter table public.app_users              enable row level security;
alter table public.employees              enable row level security;
alter table public.employee_private       enable row level security;
alter table public.onboarding_invites     enable row level security;
alter table public.employee_documents     enable row level security;
alter table public.id_cards               enable row level security;
alter table public.passkeys               enable row level security;
alter table public.notification_templates enable row level security;
alter table public.notifications          enable row level security;
alter table public.audit_log              enable row level security;

-- Tenants: members read their own company; company admins edit branding.
create policy tenants_read on public.tenants for select to authenticated
  using (id = public.current_tenant_id());
create policy tenants_update on public.tenants for update to authenticated
  using (id = public.current_tenant_id() and public.has_role('company_admin'))
  with check (id = public.current_tenant_id());

create policy domains_read on public.tenant_domains for select to authenticated
  using (tenant_id = public.current_tenant_id());

-- Masters: everyone in the tenant reads; HR writes.
do $$
declare t text;
begin
  foreach t in array array['plants','departments','designations'] loop
    execute format('create policy %I on public.%I for select to authenticated using (tenant_id = public.current_tenant_id())', t || '_read', t);
    execute format('create policy %I on public.%I for all to authenticated using (tenant_id = public.current_tenant_id() and public.is_hr()) with check (tenant_id = public.current_tenant_id() and public.is_hr())', t || '_write', t);
  end loop;
end $$;

-- Users: everyone sees their own row; HR sees all users of the tenant; company admin manages.
create policy app_users_self on public.app_users for select to authenticated
  using (id = auth.uid());
create policy app_users_hr_read on public.app_users for select to authenticated
  using (tenant_id = public.current_tenant_id() and public.is_hr());
create policy app_users_admin_write on public.app_users for update to authenticated
  using (tenant_id = public.current_tenant_id() and public.has_role('company_admin'))
  with check (tenant_id = public.current_tenant_id());

-- Employees: HR full access; managers read their team; employees read themselves.
create policy employees_hr on public.employees for all to authenticated
  using (tenant_id = public.current_tenant_id() and public.is_hr())
  with check (tenant_id = public.current_tenant_id() and public.is_hr());
create policy employees_self on public.employees for select to authenticated
  using (id = public.current_employee_id());
create policy employees_team on public.employees for select to authenticated
  using (tenant_id = public.current_tenant_id() and public.has_role('manager') and public.is_in_my_team(id));
create policy employees_payroll on public.employees for select to authenticated
  using (tenant_id = public.current_tenant_id() and public.has_role('payroll'));

-- Private (bank / statutory): HR and payroll, plus the employee themselves (read only).
create policy private_hr on public.employee_private for all to authenticated
  using (tenant_id = public.current_tenant_id() and public.has_role('hr_manager','hr_executive','payroll'))
  with check (tenant_id = public.current_tenant_id() and public.has_role('hr_manager','hr_executive','payroll'));
create policy private_self on public.employee_private for select to authenticated
  using (employee_id = public.current_employee_id());

create policy invites_hr on public.onboarding_invites for all to authenticated
  using (tenant_id = public.current_tenant_id() and public.is_hr())
  with check (tenant_id = public.current_tenant_id() and public.is_hr());

create policy docs_hr on public.employee_documents for all to authenticated
  using (tenant_id = public.current_tenant_id() and public.is_hr())
  with check (tenant_id = public.current_tenant_id() and public.is_hr());
create policy docs_self on public.employee_documents for select to authenticated
  using (employee_id = public.current_employee_id());

create policy id_cards_hr on public.id_cards for all to authenticated
  using (tenant_id = public.current_tenant_id() and public.is_hr())
  with check (tenant_id = public.current_tenant_id() and public.is_hr());
create policy id_cards_self on public.id_cards for select to authenticated
  using (employee_id = public.current_employee_id());

create policy passkeys_self_read on public.passkeys for select to authenticated
  using (user_id = auth.uid());
create policy passkeys_self_delete on public.passkeys for delete to authenticated
  using (user_id = auth.uid());

create policy templates_read on public.notification_templates for select to authenticated
  using (tenant_id = public.current_tenant_id() and public.is_hr());
create policy templates_write on public.notification_templates for all to authenticated
  using (tenant_id = public.current_tenant_id() and public.has_role('hr_manager'))
  with check (tenant_id = public.current_tenant_id() and public.has_role('hr_manager'));

create policy notifications_hr on public.notifications for select to authenticated
  using (tenant_id = public.current_tenant_id() and public.is_hr());

create policy audit_admin on public.audit_log for select to authenticated
  using (tenant_id = public.current_tenant_id() and public.has_role('hr_manager'));

-- =====================================================================
-- Storage buckets
--   branding       public  — logos shown on login page, emails and ID cards
--   employee-docs  private — Aadhaar, PAN, cheques, certificates, selfies.
--                            No client policies: the app issues short-lived
--                            signed URLs only after checking the user's role.
-- =====================================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('branding', 'branding', true, 2097152, array['image/png','image/jpeg','image/webp','image/svg+xml']),
  ('employee-docs', 'employee-docs', false, 10485760, array['image/png','image/jpeg','image/webp','application/pdf'])
on conflict (id) do nothing;


-- =====================================================================
-- 0002_attendance_leave.sql
-- =====================================================================
-- =====================================================================
-- HRM Suite — Phase 2: Attendance + Leave
-- Run after 0001_foundation.sql (Supabase SQL editor or `supabase db push`).
-- Safe to run once on a database that already holds Phase 1 data.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Shifts and holidays
-- ---------------------------------------------------------------------
create table public.shifts (
  id                 uuid primary key default gen_random_uuid(),
  tenant_id          uuid not null references public.tenants(id) on delete cascade,
  code               text not null,                  -- G, A, B, C ...
  name               text not null,
  start_time         time not null,
  end_time           time not null,                  -- earlier than start_time = ends next day (night shift)
  break_minutes      integer not null default 30 check (break_minutes between 0 and 240),
  grace_in_minutes   integer not null default 10 check (grace_in_minutes between 0 and 120),
  grace_out_minutes  integer not null default 10 check (grace_out_minutes between 0 and 120),
  half_day_minutes   integer not null default 240 check (half_day_minutes between 60 and 900),
  full_day_minutes   integer not null default 450 check (full_day_minutes between 60 and 1200),
  active             boolean not null default true,
  created_at         timestamptz not null default now(),
  unique (tenant_id, code),
  check (half_day_minutes < full_day_minutes)
);

create table public.holidays (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  plant_id      uuid references public.plants(id) on delete cascade,   -- null = every plant
  holiday_date  date not null,
  name          text not null,
  created_at    timestamptz not null default now(),
  unique nulls not distinct (tenant_id, plant_id, holiday_date)
);
create index on public.holidays(tenant_id, holiday_date);

-- Attendance settings on the employee record
alter table public.employees
  add column shift_id      uuid references public.shifts(id) on delete set null,   -- null = detect from the first punch
  add column weekly_offs   smallint[] not null default '{0}',                      -- 0 = Sunday ... 6 = Saturday
  add column attendance_id text;                                                   -- user / enrol number on the biometric device
alter table public.employees
  add constraint employees_attendance_id_unique unique (tenant_id, attendance_id),
  add constraint employees_weekly_offs_valid check (weekly_offs <@ array[0,1,2,3,4,5,6]::smallint[]);

-- ---------------------------------------------------------------------
-- Biometric devices and raw punches
-- ---------------------------------------------------------------------
create table public.attendance_devices (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  plant_id      uuid references public.plants(id) on delete set null,
  name          text not null,
  kind          text not null default 'api' check (kind in ('api','adms')),
  serial_no     text unique,                     -- ADMS (eSSL / ZKTeco push) devices identify themselves by serial
  key_hash      text unique,                     -- sha256 of the API key; the key itself is shown once
  last_seen_at  timestamptz,
  last_ip       text,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  check (kind <> 'adms' or serial_no is not null),
  check (kind <> 'api' or key_hash is not null)
);
create index on public.attendance_devices(tenant_id);

create table public.attendance_punches (
  id             bigserial primary key,
  tenant_id      uuid not null references public.tenants(id) on delete cascade,
  employee_id    uuid references public.employees(id) on delete cascade,   -- null until the device user is matched
  attendance_id  text not null,                   -- as sent by the device (or the employee code for manual punches)
  punched_at     timestamptz not null,
  device_id      uuid references public.attendance_devices(id) on delete set null,
  source         text not null check (source in ('device','csv','manual','regularisation')),
  direction      text check (direction is null or direction in ('in','out')),
  created_by     uuid references auth.users(id),
  created_at     timestamptz not null default now(),
  unique (tenant_id, attendance_id, punched_at)
);
create index on public.attendance_punches(tenant_id, employee_id, punched_at);
create index on public.attendance_punches(tenant_id, punched_at) where employee_id is null;

-- One processed row per employee per day
create table public.attendance_days (
  tenant_id        uuid not null references public.tenants(id) on delete cascade,
  employee_id      uuid not null references public.employees(id) on delete cascade,
  work_date        date not null,
  shift_id         uuid references public.shifts(id) on delete set null,
  first_in         timestamptz,
  last_out         timestamptz,
  punch_count      integer not null default 0,
  worked_minutes   integer not null default 0,
  late_minutes     integer not null default 0,
  early_minutes    integer not null default 0,
  ot_minutes       integer not null default 0,
  status           text not null check (status in (
                     'present','half_day','absent','missed_punch','weekly_off','holiday','leave','half_leave')),
  present_days     numeric(3,1) not null default 0,   -- what payroll counts
  leave_days       numeric(3,1) not null default 0,
  absent_days      numeric(3,1) not null default 0,
  leave_type_code  text,
  remarks          text,
  computed_at      timestamptz not null default now(),
  primary key (employee_id, work_date)
);
create index on public.attendance_days(tenant_id, work_date);

create table public.regularisation_requests (
  id                uuid primary key default gen_random_uuid(),
  tenant_id         uuid not null references public.tenants(id) on delete cascade,
  employee_id       uuid not null references public.employees(id) on delete cascade,
  work_date         date not null,
  in_time           time,
  out_time          time,                          -- earlier than in_time = next day
  reason            text not null check (length(reason) between 3 and 500),
  status            text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  decided_by        uuid references auth.users(id),
  decided_at        timestamptz,
  decision_comment  text,
  created_by        uuid references auth.users(id),
  created_at        timestamptz not null default now(),
  check (in_time is not null or out_time is not null)
);
create index on public.regularisation_requests(tenant_id, status);
create index on public.regularisation_requests(employee_id, work_date);

-- ---------------------------------------------------------------------
-- Leave
-- ---------------------------------------------------------------------
create table public.leave_types (
  id                    uuid primary key default gen_random_uuid(),
  tenant_id             uuid not null references public.tenants(id) on delete cascade,
  code                  text not null check (code ~ '^[A-Z0-9]{1,6}$'),
  name                  text not null,
  annual_quota          numeric(5,1) not null default 0 check (annual_quota >= 0),
  accrual               text not null default 'yearly' check (accrual in ('yearly','monthly','none')),
  carry_forward_max     numeric(5,1) not null default 0 check (carry_forward_max >= 0),
  requires_balance      boolean not null default true,    -- false for loss of pay
  paid                  boolean not null default true,
  allow_half_day        boolean not null default true,
  count_non_working     boolean not null default false,   -- true = weekly offs / holidays inside the range are counted
  min_notice_days       integer not null default 0 check (min_notice_days between 0 and 90),
  max_days_per_request  numeric(5,1) check (max_days_per_request is null or max_days_per_request > 0),
  color                 text not null default '#2563EB',
  sort_order            integer not null default 100,
  active                boolean not null default true,
  created_at            timestamptz not null default now(),
  unique (tenant_id, code)
);

create table public.leave_requests (
  id                uuid primary key default gen_random_uuid(),
  tenant_id         uuid not null references public.tenants(id) on delete cascade,
  employee_id       uuid not null references public.employees(id) on delete cascade,
  leave_type_id     uuid not null references public.leave_types(id),
  from_date         date not null,
  to_date           date not null,
  half_day          text not null default 'none' check (half_day in ('none','first_half','second_half')),
  days              numeric(5,1) not null check (days > 0),
  reason            text,
  status            text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  decided_by        uuid references auth.users(id),
  decided_at        timestamptz,
  decision_comment  text,
  cancelled_at      timestamptz,
  created_by        uuid references auth.users(id),
  created_at        timestamptz not null default now(),
  check (to_date >= from_date),
  check (half_day = 'none' or from_date = to_date)
);
create index on public.leave_requests(tenant_id, status);
create index on public.leave_requests(employee_id, from_date);

-- Every change to a balance is a ledger row, so balances can always be explained.
create table public.leave_ledger (
  id             bigserial primary key,
  tenant_id      uuid not null references public.tenants(id) on delete cascade,
  employee_id    uuid not null references public.employees(id) on delete cascade,
  leave_type_id  uuid not null references public.leave_types(id) on delete cascade,
  leave_year     integer not null,               -- year in which the leave year starts
  entry_date     date not null default current_date,
  kind           text not null check (kind in ('opening','accrual','carry_forward','availed','reversal','adjustment','lapse')),
  days           numeric(6,2) not null,          -- + credit, - debit
  period         text,                           -- accrual period ('2026' or '2026-10'); makes grants idempotent
  request_id     uuid references public.leave_requests(id) on delete set null,
  note           text,
  created_by     uuid references auth.users(id),
  created_at     timestamptz not null default now()
);
create index on public.leave_ledger(employee_id, leave_year);
create unique index leave_ledger_once_per_period on public.leave_ledger(employee_id, leave_type_id, kind, period)
  where period is not null;

create view public.leave_balances with (security_invoker = true) as
  select tenant_id, employee_id, leave_type_id, leave_year,
         sum(days) filter (where kind in ('opening','accrual','carry_forward','adjustment','lapse')) as credited,
         -sum(days) filter (where kind in ('availed','reversal'))                                    as availed,
         sum(days)                                                                                 as balance
    from public.leave_ledger
   group by tenant_id, employee_id, leave_type_id, leave_year;

-- =====================================================================
-- Functions
-- =====================================================================

-- Stores punches from a device / CSV / manual entry. Matches the device user to an employee
-- by attendance_id, falling back to the employee code. Duplicates are ignored.
-- Returns the punches that were new, so the app can recompute those days.
create or replace function public.ingest_punches(p_tenant uuid, p_device uuid, p_source text, p_rows jsonb, p_actor uuid default null)
returns table (employee_id uuid, punched_at timestamptz)
language plpgsql security definer set search_path = public as $$
#variable_conflict use_column
begin
  return query
  with rows as (
    select trim(r->>'attendance_id') as att, (r->>'punched_at')::timestamptz as ts, nullif(r->>'direction','') as dir
      from jsonb_array_elements(p_rows) r
     where coalesce(trim(r->>'attendance_id'),'') <> '' and r->>'punched_at' is not null
  ), matched as (
    select r.*, coalesce(
             (select e.id from public.employees e where e.tenant_id = p_tenant and e.attendance_id = r.att),
             (select e.id from public.employees e where e.tenant_id = p_tenant and e.attendance_id is null and e.employee_code = r.att)
           ) as emp
      from rows r
  ), ins as (
    insert into public.attendance_punches as ap (tenant_id, employee_id, attendance_id, punched_at, device_id, source, direction, created_by)
    select p_tenant, m.emp, m.att, m.ts, p_device, p_source, m.dir, p_actor from matched m
    on conflict (tenant_id, attendance_id, punched_at) do nothing
    returning ap.employee_id, ap.punched_at
  )
  select ins.employee_id, ins.punched_at from ins;
end $$;
revoke all on function public.ingest_punches(uuid, uuid, text, jsonb, uuid) from public, anon, authenticated;

-- When HR sets or changes an employee's attendance ID, earlier unmatched punches are linked.
create or replace function public.link_unmatched_punches() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.attendance_id is distinct from old.attendance_id or new.employee_code is distinct from old.employee_code then
    update public.attendance_punches set employee_id = new.id
     where tenant_id = new.tenant_id and employee_id is null
       and attendance_id in (new.attendance_id, case when new.attendance_id is null then new.employee_code end);
  end if;
  return new;
end $$;
create trigger employees_link_punches after update of attendance_id, employee_code on public.employees
  for each row execute function public.link_unmatched_punches();

-- Manager or HR may decide on this employee's requests.
create or replace function public.can_approve_for(emp uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.employees e where e.id = emp and e.tenant_id = public.current_tenant_id())
     and emp is distinct from public.current_employee_id()
     and (public.is_hr() or (public.has_role('manager') and public.is_in_my_team(emp)))
$$;

-- Default shifts and leave types, added to the Phase 1 defaults for new companies.
create or replace function public.seed_tenant_defaults(p_tenant uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  insert into public.departments(tenant_id, name, code) values
    (p_tenant,'Production','PRD'),(p_tenant,'Quality','QA'),(p_tenant,'Maintenance','MNT'),
    (p_tenant,'Stores','STR'),(p_tenant,'Production Planning & Control','PPC'),
    (p_tenant,'Human Resources','HR'),(p_tenant,'Accounts & Finance','FIN'),
    (p_tenant,'Purchase','PUR'),(p_tenant,'Engineering','ENG'),(p_tenant,'EHS','EHS')
  on conflict do nothing;
  insert into public.designations(tenant_id, name, grade) values
    (p_tenant,'Operator','W1'),(p_tenant,'Senior Operator','W2'),(p_tenant,'Technician','W3'),
    (p_tenant,'Supervisor','S1'),(p_tenant,'Engineer','S2'),(p_tenant,'Senior Engineer','S3'),
    (p_tenant,'Assistant Manager','M1'),(p_tenant,'Manager','M2'),(p_tenant,'Senior Manager','M3'),
    (p_tenant,'Head of Department','M4')
  on conflict do nothing;
  insert into public.shifts(tenant_id, code, name, start_time, end_time, break_minutes, half_day_minutes, full_day_minutes) values
    (p_tenant,'G','General shift','09:00','17:30',30,240,450),
    (p_tenant,'A','First shift','06:00','14:30',30,240,450),
    (p_tenant,'B','Second shift','14:30','23:00',30,240,450),
    (p_tenant,'C','Night shift','23:00','06:00',30,210,390)
  on conflict do nothing;
  insert into public.leave_types(tenant_id, code, name, annual_quota, accrual, carry_forward_max, requires_balance, paid, allow_half_day, min_notice_days, color, sort_order) values
    (p_tenant,'CL','Casual leave',12,'yearly',0,true,true,true,0,'#2563EB',10),
    (p_tenant,'SL','Sick leave',12,'yearly',0,true,true,true,0,'#DC2626',20),
    (p_tenant,'EL','Earned leave',15,'monthly',45,true,true,false,7,'#059669',30),
    (p_tenant,'CO','Compensatory off',0,'none',0,true,true,true,0,'#7C3AED',40),
    (p_tenant,'LOP','Loss of pay',0,'none',0,false,false,true,0,'#6B7280',90)
  on conflict do nothing;
end $$;

-- Existing companies get the new defaults too
select public.seed_tenant_defaults(id) from public.tenants;

-- Audit trail for configuration and requests (punches and daily rows are high-volume and have their own history)
do $$
declare t text;
begin
  foreach t in array array['shifts','holidays','attendance_devices','leave_types','leave_requests','regularisation_requests'] loop
    execute format('create trigger %I after insert or update or delete on public.%I
                    for each row execute function public.audit_row()', t || '_audit', t);
  end loop;
end $$;

-- =====================================================================
-- Row-level security
-- =====================================================================
alter table public.shifts                  enable row level security;
alter table public.holidays                enable row level security;
alter table public.attendance_devices      enable row level security;
alter table public.attendance_punches      enable row level security;
alter table public.attendance_days         enable row level security;
alter table public.regularisation_requests enable row level security;
alter table public.leave_types             enable row level security;
alter table public.leave_requests          enable row level security;
alter table public.leave_ledger            enable row level security;

-- Setup lists: everyone in the company reads, HR writes.
do $$
declare t text;
begin
  foreach t in array array['shifts','holidays','leave_types'] loop
    execute format('create policy %I on public.%I for select to authenticated using (tenant_id = public.current_tenant_id())', t || '_read', t);
    execute format('create policy %I on public.%I for all to authenticated using (tenant_id = public.current_tenant_id() and public.is_hr()) with check (tenant_id = public.current_tenant_id() and public.is_hr())', t || '_write', t);
  end loop;
end $$;

create policy devices_hr on public.attendance_devices for all to authenticated
  using (tenant_id = public.current_tenant_id() and public.is_hr())
  with check (tenant_id = public.current_tenant_id() and public.is_hr());

-- Attendance data: HR full; payroll reads; managers read their team; employees read their own.
do $$
declare t text;
begin
  foreach t in array array['attendance_punches','attendance_days','leave_ledger'] loop
    execute format('create policy %I on public.%I for all to authenticated using (tenant_id = public.current_tenant_id() and public.is_hr()) with check (tenant_id = public.current_tenant_id() and public.is_hr())', t || '_hr', t);
    execute format('create policy %I on public.%I for select to authenticated using (tenant_id = public.current_tenant_id() and public.has_role(''payroll''))', t || '_payroll', t);
    execute format('create policy %I on public.%I for select to authenticated using (tenant_id = public.current_tenant_id() and public.has_role(''manager'') and public.is_in_my_team(employee_id))', t || '_team', t);
    execute format('create policy %I on public.%I for select to authenticated using (employee_id = public.current_employee_id())', t || '_self', t);
  end loop;
end $$;

-- Requests: employees create their own (pending only); decisions go through the app,
-- which checks can_approve_for() and writes with the service role.
do $$
declare t text;
begin
  foreach t in array array['leave_requests','regularisation_requests'] loop
    execute format('create policy %I on public.%I for select to authenticated using (tenant_id = public.current_tenant_id() and public.is_hr())', t || '_hr', t);
    execute format('create policy %I on public.%I for select to authenticated using (tenant_id = public.current_tenant_id() and public.has_role(''payroll''))', t || '_payroll', t);
    execute format('create policy %I on public.%I for select to authenticated using (tenant_id = public.current_tenant_id() and public.has_role(''manager'') and public.is_in_my_team(employee_id))', t || '_team', t);
    execute format('create policy %I on public.%I for select to authenticated using (employee_id = public.current_employee_id())', t || '_self', t);
    execute format('create policy %I on public.%I for insert to authenticated with check (employee_id = public.current_employee_id() and tenant_id = public.current_tenant_id() and status = ''pending'')', t || '_self_insert', t);
  end loop;
end $$;


-- =====================================================================
-- Your company, plant, web address and first admin
-- =====================================================================
do $$
declare
  s record;
  v_tenant uuid;
  v_user uuid;
begin
  select * into s from hrm_setup;
  insert into public.tenants (slug, name, legal_name, emp_code_prefix)
  values (lower(s.company_slug), s.company_name, nullif(s.legal_name, ''), upper(s.emp_code_prefix))
  returning id into v_tenant;

  perform public.seed_tenant_defaults(v_tenant);   -- departments, designations, shifts, leave types

  if coalesce(s.web_address, '') <> '' then
    insert into public.tenant_domains (domain, tenant_id, is_primary, verified)
    values (lower(s.web_address), v_tenant, true, true);
  end if;
  if coalesce(s.plant_code, '') <> '' then
    insert into public.plants (tenant_id, code, name) values (v_tenant, upper(s.plant_code), s.plant_name);
  end if;

  select id into v_user from auth.users where lower(email) = lower(s.admin_email);
  insert into public.app_users (id, tenant_id, role, full_name, email, must_change_password)
  values (v_user, v_tenant, 'company_admin', s.admin_name, lower(s.admin_email), false);

  raise notice 'HRM SETUP COMPLETE — company "%" (slug %), admin %', s.company_name, lower(s.company_slug), lower(s.admin_email);
end $$;

drop table hrm_setup;

select 'HRM SETUP COMPLETE' as result,
       (select count(*) from public.tenants)     as companies,
       (select count(*) from public.shifts)      as shifts,
       (select count(*) from public.leave_types) as leave_types,
       (select count(*) from public.app_users)   as admin_logins;
