-- =====================================================================
-- HRM Suite — COMPLETE SUPABASE SETUP (Phase 1 + Phase 2 in one file)
-- For a NEW, EMPTY Supabase project.   Generated by scripts/build-setup-sql.mjs
--
-- BEFORE RUNNING
--   1. Supabase → Authentication → Users → "Add user" → "Create new user":
--      your admin email + a password, tick "Auto Confirm User".
--   2. Edit the values in "YOUR COMPANY" just below (keep the quotes).
--   3. SQL Editor → New query → paste this WHOLE file → Run.
--      Success ends with:  HRM SETUP COMPLETE
--
-- If anything is wrong (tables already exist, admin login not found) the script stops
-- before changing anything and tells you why.
-- =====================================================================

-- ------------------------- YOUR COMPANY ------------------------------
create temp table hrm_setup as select
  'kmr'                        ::text as company_slug,     -- short id, lowercase, no spaces
  'KMR'                        ::text as company_name,     -- shown in the app
  'KMR Group of Companies'     ::text as legal_name,       -- shown on ID cards and letters
  'KMR'                        ::text as emp_code_prefix,  -- employee codes: KMR-0001, KMR-0002 …
  'hrm.kmr-groups.com'         ::text as web_address,      -- the address the app opens on ('' if none)
  'HO'                         ::text as plant_code,
  'Head Office'                ::text as plant_name,
  'hr@kmr-groups.com'          ::text as admin_email,      -- the login you created in step 1
  'HR Admin'                   ::text as admin_name;
-- ---------------------------------------------------------------------

-- Safety checks: nothing is created if these fail
do $$
declare s record;
begin
  select * into s from hrm_setup;
  if to_regclass('hrm.tenants') is not null then
    raise exception 'HRM tables already exist in this database. This file is for a new, empty project. To upgrade an existing Phase 1 database, run only supabase/migrations/0002_attendance_leave.sql.';
  end if;
  if not exists (select 1 from auth.users where lower(email) = lower(s.admin_email)) then
    raise exception 'No login found for %. First create it: Authentication → Users → Add user → Create new user (tick Auto Confirm User), then run this file again.', s.admin_email;
  end if;
  if s.company_slug !~ '^[a-z0-9-]{2,30}$' then
    raise exception 'company_slug must be 2–30 lowercase letters, digits or dashes (got %).', s.company_slug;
  end if;
end $$;
